[package]
name = "roam-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Language bindings codegen for roam"

[dependencies]
heck = "0.5"
roam-hash = { path = "../roam-hash" }
roam-schema = { path = "../roam-schema" }

[dev-dependencies]
roam = { path = "../roam" }
