[package]
name = "roam-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Language bindings codegen for roam"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
heck = "0.5"
roam-hash = { path = "../roam-hash" }
roam-schema = { path = "../roam-schema" }

[dev-dependencies]
roam = { path = "../roam" }
