[package]
name = "roam-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Language bindings codegen for roam"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet-core.workspace = true
heck = "0.5"
roam-hash.workspace = true
roam-schema.workspace = true
roam-types.workspace = true

[dev-dependencies]
facet.workspace = true
roam.workspace = true
