[package]
name = "rapace-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Language bindings codegen for Rapace"

[dependencies]
rapace-hash = { path = "../rapace-hash" }
rapace-schema = { path = "../rapace-schema" }
