[package]
name = "xtask"
version = "0.6.0"
edition = "2024"
publish = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet.workspace = true
facet-args = { git = "https://github.com/facet-rs/facet", branch = "main" }
xshell = "0.2"
roam-codegen = { path = "../rust/roam-codegen" }
spec-proto = { path = "../spec/spec-proto" }
