[package]
name = "struct-test"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = { git = "https://github.com/facet-rs/facet", branch = "main" }
facet-postcard = { git = "https://github.com/facet-rs/facet", branch = "main" }
