[package]
name = "rapace-transport-shm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared memory transport for rapace (performance reference implementation)"

[dependencies]
rapace-core.workspace = true
tokio.workspace = true
libc.workspace = true

[dev-dependencies]
rapace-testkit.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
