[package]
name = "roam-schema"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rust-level schema structs per docs/content/rust-spec"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet.workspace = true
facet-core.workspace = true
roam-core.workspace = true
roam-types.workspace = true
